spring.application.name=bankClone
server.port=3000
spring.profiles.active=${ACTIVE_PROFILE:dev}

spring.datasource.url=jdbc:postgresql://localhost:5432/bankClone
spring.datasource.username=postgres
spring.datasource.password=postgres123
